### ISSUE TITLE
problem when using other twitter accounts, just my account which make app by it work fine.

### ISSUE THREAD

**Issue by mohamdio** [StanScates/Tweet.js-Mod#1]
hi, first thanks for your update in this plugin

now i using your update for seaofclouds / tweet. 
and working fine with me ...okay

but i need to ask about something : 
i using this plugin in my themes , which sure more people can use theme , so are every one will need to create his own twitter app to can make this plugin work fine ...?
because when it try to use other twitter account , all time give me my tweets enough ..!!!!!

so are every one when use my theme will need to create his app ..???

to fill this options : 

// Your Twitter App Consumer Key
    private $consumer_key    = 'YOUR_CONSUMER_KEY';

```
// Your Twitter App Consumer Secret
private $consumer_secret = 'YOUR_CONSUMER_SECRET';

// Your Twitter App Access Token
private $user_token      = 'YOUR_ACCESS_TOKEN';

// Your Twitter App Access Token Secret
private $user_secret     = 'YOUR_ACCESS_TOKEN_SECRET';
```

**Comment by StanScates** [comment]
Hey Mandooox,

First off, thanks for helping me test this out :)

And yeah, although you can use a single Twitter App to pull feeds from any public timeline, I would suggest that you advise people who use your theme to make a Twitter App of their own, using the same twitter App for everybody would cause problems very quickly with rate limiting and it would defeat the purpose of what Twitter is trying to do with their new API.

Personally, due to the somewhat user-unfriendly nature of having to configure OAuth credentials, I might suggest that for your themes you try using one of Twitter's embedded timelines and styling it the way you want with CSS, that way people who use your themes wouldn't have to configure anything, but they wouldn't be able to use some features of [seaofclouds / tweet](https://github.com/seaofclouds/tweet). 

What Twitter has done with their new API is really unfortunate, making server-side authentication necessary just to view publicly accessible information. This makes it more difficult for everybody to integrate with Twitter.

However, if I were you, and I really wanted to use this in my themes, (assuming you're talking about Wordpress), I'd probably set up a new hook in the wp-admin menu where your users can enter their OAuth credentials in the Wordpress admin instead of having to edit a PHP file, and maybe include some graphics on creating the app and etc... Just my 0.02.

Hope this helps :)

**Comment by cwulff** [comment]
I'm not sure if I'm having the same issue as Mandooox. 

I'm actually just trying to set up a friend's twitter feed and didn't think they would know how to do the whole app setup thing, so did it myself with the intention of using the **username: "unicamp_on"** from seaoftweets, but instead the app is returning tweets from my own feed, despite having their ID in username. Any thoughts as to why Twitter is only loading tweets from my own feed?

**Comment by StanScates** [comment]
Hey cwulff :)

I've just issued a hotfix for this. Replace your jquery.tweet.js with the new one (v1.3.1), (you don't need to replace index.php),  and you shouldn't experience this issue any more. 

Thanks so much for bringing this to my attention. Please let me know if you're still having troubles or I can be of any other assistance.

EDIT: I believe this will resolve Mandooox's issue as well, perhaps I didn't realize the nature of his inquiry before. 

-Stan

**Comment by cwulff** [comment]
Perfect! Thanks very much.

**Comment by mohamdio** [comment]
hi, @StanScates  , many thanks for your replay

and i just was sure from that is should ( use a single Twitter App ) :( 
whatever i was using this plugin in custom widget in my themes , and sure now i will create new options to can add APP data by user to can make plugin work fine, and also i will see to using one of Twitter's embedded timelines ..

finally very thanks again for you...
