### ISSUE TITLE
Data is null

### ISSUE THREAD

**Issue by RiccardoRics** [StanScates/Tweet.js-Mod#14]
Hi, got this error message in firebug:

TypeError: data is null
if(data.message) {

row 277

**Comment by pseudonymus** [comment]
Got the same error too. I"m working on localhost, but I don`t think that this might be the issue.

**Comment by pseudonymus** [comment]
It looks like on a real server is working fine...probably the issue is related to some localhost PHP settings which are not configured properly or disabled.

**Comment by RiccardoRics** [comment]
I've the problem on a real server, didn't tried in local.

**Comment by pseudonymus** [comment]
@RiccardoRics Then you probably have some issues with some server settings.

**Comment by RiccardoRics** [comment]
I've a shared hosting where i can set the php version, now is 5.2.17 and i'm trying now to switch it to 5.4.12.
But i don't know if i can solve the problem this way.
Always from the shared hosting panel i can modifiy the php.ini file, but also here i don't know if i have to.

**Comment by pseudonymus** [comment]
@RiccardoRics Not sure what the problem might be, you know, but keep searching for it.

**Comment by RiccardoRics** [comment]
Unfurtunatelly i got limited knowledge on these kind of stuff...

**Comment by mtthlm** [comment]
If you turn on debugging, the console reads

```
tweet.js: Couldn't resolve host '['    ...    jquery.tweet.js:277
Uncaught TypeError: Cannot read property 'statuses' of null    ...    jquery.tweet.js:285
```

I'm having issues with this, and can't seem to get this implementation to work out of the box.  Can anyone help?

**Comment by alanjenglish** [comment]
> I've a shared hosting where i can set the php version, now is 5.2.17 and i'm trying now to switch it to 5.4.12.
> But i don't know if i can solve the problem this way.

I have experienced a problem with shared hosting on Windows 2003 Server and PHP 5.2 and upgrading to Windows 2008 Server and PHP 5.4 solved the problem of tweets not loading, so it's definitely worth a go.

**Comment by markdwhite** [comment]
For me, this error at JS:277 was down to not having the path to the libs setup correctly because the default directory structure didn't work for me. 

It's working nicely. Props to the author!

**Comment by TheNinthFox** [comment]
> "tweet.js: Couldn't resolve host '['    ...    jquery.tweet.js:277
> Uncaught TypeError: Cannot read property 'statuses' of null    ...    jquery.tweet.js:285"

I have been struggling with this error for some time now and have seem to found a solution. First of all, the project I am working on requires me to use an old jQuery version (1.3.2) which causes trouble. So make sure **your jQuery is up to date** if possible.
Second of all, the tweet.js tries to **nest objects in the $_POST** which does not work for some reason. E.g. structure being like _array('request' => [object Object])_ so getting the needed data fails. This issue might also relate the old jQuery version, but I am not entirely sure.

I have found a solution which seems to work for me. Since I am not quite sure about the origin of this problem and whether it is connected to the outdated jQuery library, I am not going to submit anything into git at this point. Still you can download my fix here: https://www.dropbox.com/s/2a1thwuu9nkun32/twitter.zip

Changes made to the files are the following:
index.php line 24
jquery.tweet.js line 270, 274 - 278

Here is how it works: Basically I am just sending the whole object as a json-formatted string, create an array from that string in the index.php, return the response as a string and not json, since the ajax function does not seem to support the dataType "json" at that point and turn the json string back into a js object.

**Comment by julianfe** [comment]
Can confirm. Had it working on four sites but not a fifth one. Was using jquery-1.3.2.js. Amended to http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js. Worked straight away with no hacks needed

**Comment by sulliwane** [comment]
Hi,

I had the same error, I upgraded to http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js and now the error is gone. But I still can't get my tweet displaying on my website (http://www.ridetheflavour.fr/) and I really don't know why...

**Comment by sulliwane** [comment]
My php version was 5.3, I set it to 5.4 => http://www.ridetheflavour.fr/twitter/phpinfo.php

no changes. I disabled the caching feature, enabled the logging, checked the Oauth credentials (all 4 are right).

Here is my jquery.tweet.js, as u can see on the second screenshot, I found another modpath ref that I replaced with absolute path as well. is it necessary ?

![twit1](https://f.cloud.github.com/assets/1733686/713467/19cde21e-decd-11e2-8323-8ff6adae843c.png)
![twit2](https://f.cloud.github.com/assets/1733686/713468/1cb02258-decd-11e2-8420-765d570d0dcd.png)
![twit3](https://f.cloud.github.com/assets/1733686/713470/1e38bda6-decd-11e2-86e1-15a7f4511c8a.png)

And here is my index.php : 
![twit4](https://f.cloud.github.com/assets/1733686/713491/b624a26a-decd-11e2-8822-2dbe31576f67.png)

**Comment by sulliwane** [comment]
OKKKK it works !!!!!

I must have another problem that I solved, but in between I modified 

```
private $lib = '/.lib/'
```

to

```
private $lib = 'http://www.ridetheflavour.fr/twitter/lib/'
```

in index.php and that was a big mistake (as you can see on the picture above). This path must be relative.

So now I'm not sure of what was the real initial problem, and what modification actually solved my problem (it could be javascript conflict removal, php 5.4 update, or even modpath 2nd ref in jquery.tweet.js)

Thank you guys for your help, alone I would have give up long time before. I've never been so happy when looking at a tweet on a web page...strange
