### ISSUE TITLE
Configuring the App

### ISSUE THREAD

**Issue by gizmecano** [StanScates/Tweet.js-Mod#28]
Greetings,

After creating the App, could you confirm there's nothing to change in the _Request Settings_ block in the _OAuth_ tab?

Indeed, I followed step by step your [_how-to_](https://github.com/StanScates/Tweet.js-Mod#how-to-use), but nothing appears on my pages, so I wonder if I missed a step during the configuration (the debug option does not write anything at all...).

Thanks.

**Comment by paultibbetts** [comment]
The script works for me without changing any settings in the OAuth tab so this can be left on **GET** with _https://api.twitter.com/1/_ as the **Request URI**.

You should only need the **Consumer Key**, **Consumer Secret**, **Access Token** and **Access Secret Token** from the Twitter App.

If you open the console on the site, what error messages are you getting?

I once had no Tweets coming up because I left the trailing slash / from the end of the modpath I'd told the script to use, worth a quick check if everything else is set up correctly.

**Comment by gizmecano** [comment]
Greetings,

Well, so the first point is established: the authentication configuration for the application seems reliable. I have the **four data** mentioned: my problem seems not be at this point.

Now, about the console, as I said before, even setting the _debug_ option, I have absolutely no error nor warning about JavaScript.

Assuming that application is configured, I think I'll take everything from the beginning, step by step... If it works elsewhere, error seems to be from my doing... :pensive:

**Comment by gizmecano** [comment]
Assuming the App configuration is correct according @ptibbetts, I close this issue and I have opened a new following issue (#29).
