### ISSUE TITLE
Loading tweets - nothing else is happening

### ISSUE THREAD

**Issue by welookwelike** [StanScates/Tweet.js-Mod#43]
Hi

Very confused on this one. I've set up the API tokens and updated everything. I have the feed working on 2 other sites (different accounts) and so am 99% sure I've set it all up correctly, however all i get is a 'loading tweets' method and nothing else.

The error console states: 

Error: TypeError: response is null
Source File: XXXXXXXXXXX/includes/twitter/jquery.tweet.js
Line: 285

Any ideas? Thanks

Site is here: http://www.wearecheekysparrow.co.uk/test-home/

**Comment by SabeBarker** [comment]
Hello :)

With my wordpress site I don't have modpath in the head tags and only have it in the modpath option within jquery.tweet.js.

I also use: $(document).ready(function()

instead of: jQuery(function($)

This shouldn't matter but I simply played with different options until it loaded my tweets.

The way you have it setup should work but have you tried adding the modpath to the js file just to see what happens?

Also check the index file as that error seems to be a 404 or something from twitter?

**Comment by welookwelike** [comment]
Update: Got it working. Thanks for you help.

**Comment by SabeBarker** [comment]
Awesome, glad you got it working! Beautifully sleek web design btw. 

What ended up fixing the issue? (for future reference)

**Comment by welookwelike** [comment]
I updated the version of jQuery, had a duplicate reference somewhere and went through and recreate the access token on Twitter. Basically a lot of fiddling of bits as you suggested.

One day I'll be able to cookie-cut the integration ONE DAY!

thanks again, and for the feedback on the website :)

**Comment by SabeBarker** [comment]
No probs :)
